steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-east1-docker.pkg.dev/soy-lore-407417/web-app-repo/web-app:latest'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-east1-docker.pkg.dev/soy-lore-407417/web-app-repo/web-app:latest'

- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  entrypoint: 'bash'
  args:
    - '-c'
    - |
         PROJECT=$$(gcloud config get-value core/project)          
         gke-gcloud-auth-plugin --version
         export USE_GKE_GCLOUD_AUTH_PLUGIN=True 
         gcloud container clusters get-credentials old-homolog-cluster --zone us-east1-c --project soy-lore-407417
         kubectl apply -f k8s/deployment.yaml