steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-east1.pkg.dev/SEU_PROJETO/SEU_REPOSITORIO/NOME_DA_IMAGEM:TAG', '.']
images:
- 'us-east1.pkg.dev/old-onepet-homolog/app/homolog:latest'
