steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-east1-docker.pkg.dev/soy-lore-407417/web-app-repo/web-app:${SHORT_SHA}'
  - '-t'
  - 'us-central1-docker.pkg.dev/pub-demo-cb-ar/python-repo/my-app:latest'
  - '--cache-from',
  - 'us-central1-docker.pkg.dev/pub-demo-cb-ar/python-repo/my-app:latest'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-east1-docker.pkg.dev/soy-lore-407417/web-app-repo/web-app:${SHORT_SHA}'

- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  entrypoint: 'bash'
  args:
    - '-c'
    - |
         SHORT_SHA=$(${SHORT_SHA})
         gcloud container clusters get-credentials old-homolog-cluster --zone us-east1-c --project soy-lore-407417
         kubectl apply -f k8s/deployment.yaml