steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '-t', 'us-east1.pkg.dev/old-onepet-homolog/app/homolog:latest', '.']
images:
- 'us-east1.pkg.dev/old-onepet-homolog/app/homolog:latest'
