apiVersion: apps/v1
kind: Deployment
metadata:
  name: $GKE_APP_NAME
  namespace: $GKE_NAMESPACE
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $GKE_APP_NAME
  template:
    metadata:
      labels:
        app: $GKE_APP_NAME
    spec:
      serviceAccountName: $GKE_SERVICE_ACCOUNT
      containers:
      - name: $GKE_APP_NAME
        image: $GKE_REGION-docker.pkg.dev/$GKE_PROJECT/$GKE_PROJECT/$GKE_APP_NAME:$GITHUB_SHA
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            value: "host de exemplo"