apiVersion: apps/v1
kind: Deployment
metadata:
  name: $GKE_APP_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $GKE_APP_NAME
  template:
    metadata:
      labels:
        app: $GKE_APP_NAME
    spec:
      #serviceAccountName: $GKE_SERVICE_ACCOUNT
      containers:
      - name: $GKE_APP_NAME
        image: $GKE_REGION-docker.pkg.dev/$GKE_PROJECT/$GKE_PROJECT/$GKE_APP_NAME:$GITHUB_SHA
        resources:
          requests: 
            cpu: "0.05"
            memory: 128Mi
          limits:
            cpu: "0.05"
            memory: 128Mi
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_HOST
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_PASSWORD