apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-php-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: $GKE_APP_NAME
    kind: Deployment
  minReplicas: 2
  maxReplicas: 30
  targetCPUUtilizationPercentage: 80