apiVersion: v1
kind: Service
metadata:
  name: $GKE_SERVICE
spec:
  selector:
    app: $GKE_APP_NAME
  type: ClusterIP
  ports:
  - name: $GKE_SERVICE
    port: 9000
    targetPort: 9000
    protocol: TCP